# Generated by Django 3.1.7 on 2021-05-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooking',
            old_name='Customer_phn_number',
            new_name='Car_rent_per_day',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='Customer_address',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='car_capacity',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='car_company',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='car_type',
        ),
    ]
