# Generated by Django 3.1.7 on 2021-05-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0003_auto_20210526_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('Customer_name', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('Car_rent_per_day', models.IntegerField()),
                ('total_no_of_days', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('advance_amount', models.IntegerField()),
                ('balance_amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CarBooking',
        ),
    ]
