# Generated by Django 3.1.7 on 2021-06-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0006_auto_20210603_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(max_length=100)),
                ('imgs', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('car_name', models.CharField(max_length=100)),
                ('car_company', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=100)),
                ('car_capacity', models.IntegerField()),
                ('car_number', models.CharField(max_length=50)),
                ('car_district', models.CharField(max_length=100)),
                ('Car_rent_per_day', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='imgs',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
