# Generated by Django 3.1.7 on 2021-06-15 08:29

import car_rental_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0007_auto_20210614_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(blank=True, null=True, upload_to=car_rental_system.models.filepath)),
                ('car_name', models.CharField(max_length=100)),
                ('car_company', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=100)),
                ('car_capacity', models.IntegerField()),
                ('car_number', models.CharField(max_length=50)),
                ('car_fuel', models.CharField(max_length=100)),
                ('car_city', models.CharField(max_length=100)),
                ('car_district', models.CharField(max_length=100)),
                ('Car_rent_per_day', models.IntegerField()),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='car',
        ),
        migrations.AddField(
            model_name='car_booking',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to=car_rental_system.models.filepath),
        ),
    ]
