# Generated by Django 3.1.7 on 2021-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0008_auto_20210615_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('car_company', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=100)),
                ('car_capacity', models.IntegerField()),
                ('car_number', models.CharField(max_length=50)),
                ('car_district', models.CharField(max_length=100)),
                ('Car_rent_per_day', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
        migrations.DeleteModel(
            name='IssueCar',
        ),
        migrations.RemoveField(
            model_name='car_booking',
            name='imgs',
        ),
    ]
