# Generated by Django 3.1.7 on 2021-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0009_auto_20210615_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('Car_rent_per_day', models.IntegerField()),
                ('total_no_of_days', models.IntegerField()),
                ('paymnent_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_no_of_days',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_name',
        ),
    ]
