# Generated by Django 3.1.7 on 2021-06-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0012_auto_20210616_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_booking',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='Car_Booking'),
        ),
        migrations.AlterField(
            model_name='car_booking',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
