# Generated by Django 3.1.7 on 2021-06-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0016_registration_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration_table',
        ),
    ]
