# Generated by Django 3.1.7 on 2021-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0018_register_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_booking',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
