# Generated by Django 3.1.7 on 2021-06-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0019_car_booking_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_booking',
            name='username',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
