# Generated by Django 3.1.7 on 2021-06-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_system', '0020_auto_20210620_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
